### ISSUE TITLE
Build / install problems (maybe lack of documentation?)

### ISSUE THREAD

**Issue by dsl101** [lkcheng89/starbook#1]
Hi,

I'd really like to try using this with my Starbook S (firmware 2.7) and Sky Chart, but I've reached the limit of my knowledge... What would be _fantastic_ would be if you were able to build an installer for the driver to add to the repo (for me, Windows 10 64-bit, but I realise there'll be other requirements).

Anyway, I downloaded all the build tool chain and bits and pieces, and I can successfully build the VS project. But I'm stuck after that. What should I do next to install it? I tried the ASCOM Driver Install Script Generator, and ran it on both the `\bin\Release` and `\obj\Release` folders. But the script it generates first of all fails a version check with Inno Setup Compiler (min version 6.0 now), and then fails on this line:
```
   P := CreateOleObject('ASCOM.Utilities.Profile');
```
I don't see a dll by that name in either output folder, so not sure what to try next... Any pointers or more detailed build / install steps much appreciated...

**Comment by dsl101** [comment]
OK, I found the .iss file in the root of the project the next day :). Using that I was able to install the built driver and connect to it. Maybe even just that simple pointer on the main readme?

**Comment by lkcheng89** [comment]
Hi, kind of be late to see this issue. This is a good idea to write a build / install doc, I will try to post this in the future. Thank you for the sharing.
